### PR TITLE
Library updates

### PR DESCRIPTION
**Pull request by caseysoftware**
- Updated phpUnit to the latest version to support tests;
- Updated minimum PHP version, technically not necessary at the moment but this minimum version is still under active support by the PHP Group - http://php.net/supported-versions.php (active support until Dec 2016, security support until Dec 218);
- Implemented all the details around Saved Queries including - creating, retrieving, updating & deleting them and getting the actual results;
- Wrote sample snippets for the documentation.

### CODE REVIEW

**Comment by josephwegner** [comment]
@caseysoftware this looks great, thank you.

One small bit of feedback:

Could we change the saved queries related functions to include the term "Saved" in the function name. For instance, change `$client->createQuery` to `$client->createSavedQuery`. The same sort of thing would apply to all the other saved query functions.

Awesome! Thanks!

**Comment by caseysoftware** [comment]
@josephwegner Thanks! Updated as requested.

Btw, the /docs folder can be deleted once that's merged in with your existing docs repo. It doesn't need to be in the final release.

**Comment by josephwegner** [comment]
Love it! +1

**Comment by josephwegner** [comment]
@caseysoftware OK, great. We will get these docs updated on our website.

Could you update the README with saved queries stuff, removed the /docs folder, and then this PR is good to merge.

**Pull request merged**
