### PR TITLE
Adds access key service descriptions

### PR DESCRIPTION
**Pull request by deweller**

### CODE REVIEW

**Comment by jaketoolson** [comment]
Any updates on adding this!?

**Comment by tbarn** [comment]
@mglaman wanna update your review?

**Comment by tbarn** [comment]
Thanks, @mglaman! ✨ 💖 

@deweller I'd feel more comfortable merging this if docs were added to the readme. Think you could add some? 

Some examples are: https://keen.io/docs/api/?javascript#access-keys 
Also, this one isn't complete, but definitely a good start: https://github.com/keenlabs/keen-gem#access-keys

**Comment by deweller** [comment]
I've abandoned this pull request.  But you are welcome to use the code if you find it helpful.

**Comment by mglaman** [comment]
I am also not actively using the SDK or this PR patch anymore to push forward changes. Took too long for feedback and activity from Keen.

**Comment by tbarn** [comment]
@deweller @mglaman totally understandable. And I apologize for how long it took for movement on this. I'm going to be working on improving this in the future for all our SDKs.

**Pull request closed without merging**
