### PR TITLE
Implement delete collection by name

### PR DESCRIPTION
**Pull request by MohammadWaleed**
This pull request implements deleting collections by name

### CODE REVIEW

**Comment by MohammadWaleed** [comment]
Hi @piotrek-buchman 

everything should be good now.

**Comment by piotrek-buchman** [comment]
@MohammadWaleed thanks for an update, but may you please change 2.5.15 to 2.6.0?

We're following the [SemVer versioning pattern](https://semver.org/). As _delete collection_ is a new feature (backward compatible) then we should bump minor version instead of patch version.

**Comment by piotrek-buchman** [comment]
@MohammadWaleed thanks for an update, but may you please change 2.5.15 to 2.6.0?

We're following the [SemVer versioning pattern](https://semver.org/). As _delete collection_ is a new feature (backward compatible) then we should bump minor version instead of patch version.

**Comment by piotrek-buchman** [comment]
@MohammadWaleed thanks for an update, but may you please change 2.5.15 to 2.6.0?

We're following the [SemVer versioning pattern](https://semver.org/). As _delete collection_ is a new feature (backward compatible) then we should bump minor version instead of patch version.

**Comment by MohammadWaleed** [comment]
> @MohammadWaleed thanks for an update, but may you please change 2.5.15 to 2.6.0?
> 
> We're following the [SemVer versioning pattern](https://semver.org/). As _delete collection_ is a new feature (backward compatible) then we should bump minor version instead of patch version.

@piotrek-buchman Done 👍

**Pull request merged**
