### PR TITLE
Update to Guzzle 6.0

### PR DESCRIPTION
**Pull request by EmilyShepherd**
Switched from the abandoned guzzle/guzzle repo to guzzlehttp/guzzle and update to Guzzle 6.0 and Guzzle-Services 1.0.

This fixes issue #90

### CODE REVIEW

**Comment by BernardoSilva** [comment]
:shipit:

**Comment by hetmansky** [comment]
+1

**Comment by BernardoSilva** [comment]
@elof could you review this and possible merge it an bump as major release?

We would like to keep this repo up to date instead of using a fork of it since we really want this changes. :)

**Comment by EmilyShepherd** [comment]
:walking_woman:

**Comment by elof** [comment]
Getting this reviewed and will have it merged v shortly

**Comment by BernardoSilva** [comment]
👍 amazing news! thank you @elof .
Looking forward for it. 

Need this to push our project into PHP7 world.

**Comment by EmilyShepherd** [comment]
Awesome! :smiley: thanks so much!

**Comment by BernardoSilva** [comment]
👍

**Comment by BernardoSilva** [comment]
Can you review please? :)

**Comment by EmilyShepherd** [comment]
Fantastic :+1: Thanks guys x

**Pull request merged**
